= mulesoft-docs-theme-default

== Prerequisites

First, you will need node, yarn and gulp. Once you have those CLI tools, you can run this to get the latest dependencies:

[source, bash]
yarn install

== Building the theme

To build the different assets of the theme, run this:
[source, bash]
gulp build-theme

All the source files will be processed and optimized into `build/_theme`.

== Building the preview page

In order to preview the theme without doing a full build of the site, this project includes a fake static page: `preview-site/index.html`.
You can build this static page with the templates included in the theme with this:

[source, bash]
gulp build-preview

== Development setup

If you work on the theme assets (CSS, JS, fonts...), it's often better to avoid building the preview manually.
This project includes a small HTTP server and a live build-reload setup.
You just have to run this:

[source, bash]
gulp serve

Once this is running in your terminal, each change to stylesheets, scripts, templates... will trigger a reload in your browser.
You can browser the preview page here: `http://localhost:8080`.
